sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project react-kubernetes-cluster
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - npm install -g snyk
  - snyk auth "$SNYK_TOKEN"
  - docker build -t dmsanthosh/react-test -f ./client/Dockerfile.test ./client
  - snyk monitor --docker dmsanthosh/react-test --file=./client/Dockerfile.test
script:
  - docker run -e CI=true dmsanthosh/react-test npm test -- --coverage
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      - secure: cu+7IgGgX98LRJYjdMq3WdWzo2iwZcGEv2jrlxBbaH58FOpSHEl4yRLT+hj5TDwRd1gTGmPPah5G48osp1TfTtjfzVx79GpueDKpoYPp3aYIDBLNGLszFKvNUqmCl2eVNe7xLhp5O5m9UKqPk34Z6Q2TaPXK7DtOHOvHJVZrS/NXw6nbG7TSILmkcUT6EvypoP27vTBoSo2WZDcHlVGRGBG7+XhogvjjUJ9AeJujeY7D2vcKhFoNaWcDfIKLKaa2lK/rTix1c2LORPag7FMZlnDqGEG20B7cGbuMu3Av2nDhsCOwC0Kt0FEY7sOF/ZU6Ai1BGUNdTPPRfHtO6SYe5UVXh6eaPrepoXN0Was4CIqhulCkaELBJq4zCowrZeys5njBE0vJ1kvokT4SMlvYeQ/rPgGtHoJjX+MnuAwvKRERVPzb4pMhTO/cb0Q3msa74DR8H0qmcnwOcw6e5w3Jlyd8OvR7jAvxg5+szJarP+JbIV7a+67FdUdeW2PPFPenIzW/wvTPRTVWoOqHNbBAhfd8vC5inzyv+ppM6lMy07EQ8mx/7SklnoW2/aDfuHS/uRjqETJEdYoyfP701PehMrfgNlEvcNV/p/O1iEJIbL6qIqiN7Hzkdy8RHjh5zzXc5+qgFSaiJRqLrar7B07YC67wYHxMDdpB/z3euq5zAG8=
