language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
notifications:
  slack:
    secure: fgD62jo/lvjfif5eCgpPUw1ylpektIO7NOmb8E8/ST9VuHdBwtndE2IRCp3+7dq6eBzvWgUXK3UfjUoyPTg5JLzZYyELljm1H6azGAhWWn0jz0NSojloaPq4sb0hbaNk1zXvqUhjLgO6DEg7jRxCNNDKUZIO38nBXDRVioBCdJxjIFVPTZunrAv5BJswXpsWRRMJSv/QX+Otk3r6miFCW90CyRufQNTbGWBmatVKNQ9pUJyjhh6moXAfHc6/xFtF1iJstOY5e33Ef/s48UFcHZonPO4pKYVeDGtX80u1GkOgaakVRcgnDDAvdy1vv/X5HJsy4RrIN6GFwX5+7F6ZisZaiASAWonWfAJ6QrfK7D7ZorjMgt1FBrvOhp5lnhlr2SYXwNPkvbn0dpRlqgAarno/g8U7yow+8RwBZX/CS2A+X7LLMOxLAapVjmh3PCHlQj02+9SwgCSdx1GzLZ38ot8wwhAnR7RuN6fQ0AknO72fH6nZYjjdAIsEJBTSvsxi483+mRYIaTzIIKZ5ZWcjz+I7hw/BFKjj4xTme32jfJKFr5b7EwKCcMKPoRHwoE+dLJpMoBymBc0r8/2KDqWho0F0X1Wwn2Em49D/i0dOi5c0A/iILLGHD+ivDKPhghVmB5poyvX9/yhGaAHfcdUIUqVwJaxg2CElHzoSanLWnt4=
